#-------------------------------
# General Site Settings

title: Date Countdown
description: I will give you a hint.

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/b/116392188754803429731/116392188754803429731/about?hl=en&service=PLUS'
  rel-publisher: 'https://plus.google.com/b/116392188754803429731/116392188754803429731/about?hl=en&service=PLUS'